### PR TITLE
Add backend position

### PR DESCRIPTION
**Pull request by llunaCreixent**
- Add backend position
- Remove commented code
- Update members

### CODE REVIEW

**Comment by llunaCreixent** [comment]
please @JacqueGM , @mikozet  review that your names are correct, for the rest of us we've put our last names, and I wonder if you want to add yours.
Then, @ana0 , are you ok having your name there as passive member? ❤️

**Review by adzialocha — CHANGES_REQUESTED** [review]
Shouldn't we specify a bit more what this role entails?

**Comment by mikozet** [comment]
> Shouldn't we specify a bit more what this role entails?

Yeah, I would write some basic requirements (in a way that would encourage for application)

**Review by louilinn — APPROVED** [review]
I think this is good enough.
We could add more but better to start the process, we will not recruit as widely this time maybe, so we can also explain more when we meet.

**Review by JacqueGM — APPROVED** [review]

**Pull request merged**
